name: molbind

channels:
  - conda-forge
  - pytorch
  - pyg
  - nvidia
  - defaults

dependencies:
  - python>=3.9
  - pip
  - chromadb
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==2.0.0+cu117
    - --editable "."
