# model architecture
encoders:
  smiles:
    pretrained: True
    freeze_encoder: False

  selfies:
    pretrained: True
    freeze_encoder: False

  fingerprint:
    "ckpt_path": "${paths.pretrained_models_dir}/fingerprint/morgan_vae.ckpt"
    "input_dim": [2048, 1024, 768]
    "output_dim": [768, 1024, 2048]
    "latent_dim": 512

projection_heads:
  smiles:
    dims: [768, 256, 128]
    activation: LeakyReLU
    batch_norm: False
  selfies: 
    dims: [768, 256, 128]
    activation: LeakyReLU
    batch_norm: False
  fingerprint:
    dims: [768, 256, 128]
    activation: LeakyReLU
    batch_norm: False

optimizer:
  lr: 0.0001
  weight_decay: 0.0001

loss:
  temperature: 0.1
    
# compile model for faster training with pytorch 2.0
compile: false
