model_checkpoint:
  dirpath: "${paths.checkpoints_dir}"
  filename: "{epoch:03d}_{valid_loss:.2f}"
  monitor: "valid_loss"
  mode: "min"
  save_top_k: 3
  save_last: False

early_stopping:
  monitor: "valid_loss"
  patience: 3
  mode: "min"