model_checkpoint:
  dirpath: "checkpoints"
  filename: "{epoch:03d}_{valid_loss:.4f}"
  monitor: "valid_loss"
  mode: "min"
  save_top_k: 3
  save_last: False

early_stopping:
  monitor: "valid_loss"
  patience: 3
  mode: "min"